### ISSUE TITLE
Row count breaks if itemSelector elements are not left aligned

### ISSUE THREAD

**Issue by JournalHumanite** [Position2/jQuery-Inline-Popup#1]
[centered_elements.patch.gz](https://github.com/Position2/jQuery-Inline-Popup/files/2200983/centered_elements.patch.gz)
Hello,
If itemSelector elements are centered, and the last line is not complete, the rows increment won't work for this line.
This is because the test on line 112 assume that all elements have the same left offset : 
` if(firstLeft == curLeft) currentRow += 1;`

In this patch, the test is done on the comparison with the previous left offset.

**Comment by JournalHumanite** [comment]
[centered_elements.patch.gz](https://github.com/Position2/jQuery-Inline-Popup/files/2201542/centered_elements.patch.gz)
Better version.

**Comment by rhenryrobert** [comment]
@JournalHumanite Thanks. We will fix this issue in our next release.
